repos:
  - name: 'DevCraft AdminPanel'
    config: crowdin.yml
    repository: https://github.com/DevCraftClub/mhadmin.git
    source: upload/
    trans_file: devcraft
  - name: 'Custom UserTags'
    config: crowdin.yml
    repository: https://github.com/DevCraftClub/tagsadd.git
    source: upload/
    trans_file: tags_add
  - name: DB-Manager
    config: crowdin.yml
    repository: https://github.com/DevCraftClub/DB-Manager.git
    source: upload/
    trans_file: db-manager
  - name: 'Re: Post'
    config: crowdin.yml
    repository: https://github.com/DevCraftClub/dle-repost.git
    source: upload/
    trans_file: repost
  - name: 'DLE Faker'
    config: crowdin.yml
    repository: https://github.com/DevCraftClub/dle_faker.git
    source: upload/
    trans_file: dle-faker
