name: Generate i18

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  generate:
    runs-on: [self-hosted, homeserver]
    permissions:
      contents: read
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v7

      - name: Show Python version
        run: python3 --version

      - name: Create virtualenv
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Generate translation sources
        run: python3 scripts/generate_i18_repos.py
